// Current Reducer Actions List with Uppercase
export const profileActions = {
  MANAGE_USER_INFO: 'MANAGE_USER_INFO',
  MANAGE_USER_GENDER: 'MANAGE_USER_GENDER',
  MANAGE_USER_PROFILE_IMAGE: 'MANAGE_USER_PROFILE_IMAGE',
  MANAGE_USER_DATE_BIRTH: 'MANAGE_USER_DATE_BIRTH'
}